baseURL = "https://euleobispo.hopto.org/"
title = "um sitezinho"
languageCode = "pt-BR"
theme = "devise"
relativeURLs = true
enableEmoji = true
enableRobotsTXT = true

# Main menu items
[menu]
  [[menu.main]]
    identifier = "sobre"
    name = "sobre"
    title = "sobre"
    url = "/sobre/"
    weight = -110
  [[menu.main]]
    identifier = "letras"
    name = "letras"
    title = "letras"
    url = "/letras/"
    weight = -100
  [[menu.main]]
    identifier = "imagens"
    name = "imagens"
    title = "imagens"
    url = "/imagens/"
    weight = -90

# Configuration Features
[params]
  description = "um sitezinho"      # Your meta description of the site
  header_title = "um sitezinho"                 # Your header title
  header_subtitle = "um espacinho na internet" # Your header subtitle
  recent_posts = 5                           # Max amount of recent posts to show
  mainSections = ["posts", "post", "blog"]   # Main sections to include in recent posts
  [params.style]                             # CSS style overrides
    backgroundColor = "#f8f9fa"
    homeImageBorderColor = "#ffffff"
    fontFamilyBase = "Helvetica Neue"        # First-choice font
    fontColor = "#212529"
